use crate::lean_vocab_test::{lean_fork_provenance_cases, LeanForkProvenanceCase};

#[allow(clippy::too_many_arguments)]
fn case(
    name: &str,
    kind: &str,
    disposition: &str,
    twins: usize,
    source_authoritative: bool,
    source_session_id: u64,
    child_session_id: u64,
    source_doc_id: u64,
    source_cid: u64,
    source_signer_did: u64,
    child_doc_id: u64,
    child_cid: u64,
    child_signer_did: u64,
    child_call_required: bool,
    child_call_satisfied: bool,
    exact_source_pinned: bool,
    immutable_noop: bool,
) -> LeanForkProvenanceCase {
    LeanForkProvenanceCase {
        name: name.to_string(),
        kind: kind.to_string(),
        disposition: disposition.to_string(),
        visible_logical_twins: twins,
        source_authoritative,
        source_session_id,
        child_session_id,
        source_doc_id,
        source_cid,
        source_signer_did,
        child_doc_id,
        child_cid,
        child_signer_did,
        child_call_required,
        child_call_satisfied,
        exact_source_pinned,
        immutable_noop,
    }
}

pub(crate) fn generated_cases_pin_exact_fork_sources() {
    let expected = vec![
        case(
            "message_child_fact_applied",
            "message",
            "applied",
            0,
            true,
            1,
            2,
            100,
            10,
            7,
            200,
            20,
            8,
            false,
            true,
            true,
            false,
        ),
        case(
            "identical_child_replay_is_idempotent",
            "message",
            "observed_identical",
            1,
            true,
            1,
            2,
            100,
            10,
            7,
            200,
            20,
            8,
            false,
            true,
            true,
            true,
        ),
        case(
            "logical_key_twins_fail_closed",
            "message",
            "rejected",
            2,
            true,
            1,
            2,
            100,
            10,
            7,
            200,
            20,
            8,
            false,
            true,
            false,
            true,
        ),
        case(
            "same_session_relabel_is_rejected",
            "message",
            "rejected",
            0,
            true,
            1,
            1,
            100,
            10,
            7,
            200,
            20,
            8,
            false,
            true,
            false,
            true,
        ),
        case(
            "wrong_node_signer_is_rejected",
            "message",
            "rejected",
            0,
            true,
            1,
            2,
            100,
            10,
            7,
            200,
            20,
            8,
            false,
            true,
            false,
            true,
        ),
        case(
            "unsigned_child_is_rejected",
            "message",
            "rejected",
            0,
            true,
            1,
            2,
            100,
            10,
            7,
            200,
            20,
            8,
            false,
            true,
            false,
            true,
        ),
        case(
            "unsigned_source_is_rejected",
            "message",
            "rejected",
            0,
            false,
            1,
            2,
            100,
            10,
            7,
            200,
            20,
            8,
            false,
            true,
            false,
            true,
        ),
        case(
            "payload_rebinding_is_rejected",
            "message",
            "rejected",
            1,
            true,
            1,
            2,
            100,
            10,
            7,
            200,
            20,
            8,
            false,
            true,
            true,
            true,
        ),
        case(
            "tool_result_pins_new_child_call",
            "tool_result",
            "applied",
            0,
            true,
            1,
            2,
            120,
            12,
            7,
            220,
            22,
            8,
            true,
            true,
            true,
            false,
        ),
        case(
            "tool_result_without_child_call_is_rejected",
            "tool_result",
            "rejected",
            0,
            true,
            1,
            2,
            120,
            12,
            7,
            220,
            22,
            8,
            true,
            false,
            false,
            true,
        ),
    ];
    assert_eq!(lean_fork_provenance_cases(), expected);
}
