//! Conformance fence for the provider-input sanitizer.
//!
//! This fence used to be *social*: a human read `Proofs/PromptAssembly` and
//! hand-wrote assertions against a test-local pairing oracle. Nothing tied the
//! Rust sanitizer to the function the Lean theorems quantify over, so a change
//! to either side could break the correspondence without failing a test. That
//! is not hypothetical — `loop_stream.rs::repair_provider_input` records a bug
//! of exactly this shape, where "the fence described a transform that did not
//! exist".
//!
//! It is now mechanical. Every expectation below is generated by running the
//! Lean model (`PromptAssembly.Provider.sanitizeForProvider`) and consumed here
//! verbatim; see `Proofs/Conformance/ContractCases/PromptAssembly.lean`.
//!
//! **There is deliberately no provider-validity oracle in this file.** Validity
//! of each expected output is the Lean theorem
//! `Provider.sanitizeForProvider_sound`. Production that reproduces the emitted
//! output exactly inherits it. Re-deriving pairing rules in Rust would just
//! reintroduce the social fence this replaces.

use gents::compaction::sanitize_history_for_provider;
use gents::llm::message::{
    AssistantContent, Message, Reasoning, Text, ToolCall, ToolFunction, ToolResult,
    ToolResultContent, UserContent,
};

use std::collections::HashSet;

use gents::claude_messages::{
    build_messages_body_native, parse_messages_sse, CLAUDE_CODE_IDENTITY,
};
use gents::claude_subscription::ClaudeStreamResponse;
use rig::completion::CompletionError;
use rig::streaming::RawStreamingChoice;

use crate::lean_vocab_test::{
    lean_prompt_assembly_claude_body_cases, lean_prompt_assembly_claude_map_cases,
    lean_prompt_assembly_claude_stream_cases, lean_prompt_assembly_sanitize_cases,
    LeanPromptAssemblyItem, LeanPromptAssemblyRow,
};

/// Stable identities for the abstract ids the model uses. The model abstracts
/// a tool call to a single `ToolCallId`; production pairs on
/// `call_id.unwrap_or(id)` (`history.rs::tool_call_key`). Both fields carry the
/// same string here so the projection is unambiguous; the case where they
/// differ is fenced separately by `pairing_identity_uses_call_id_over_item_id`.
fn call_key(id: u64) -> String {
    format!("call-{id}")
}

fn text_body(index: u64) -> String {
    format!("text-{index}")
}

fn reasoning_body(index: u64) -> String {
    format!("reasoning-{index}")
}

fn tool_call(id: u64) -> ToolCall {
    ToolCall {
        id: call_key(id),
        call_id: Some(call_key(id)),
        function: ToolFunction {
            name: "echo".to_string(),
            arguments: serde_json::json!({}),
        },
        signature: None,
        additional_params: None,
    }
}

/// Build the production `Message` a generated row denotes.
///
/// Total by construction: an unknown role, kind, or item name panics rather
/// than silently producing something the model did not describe.
fn message_of_row(row: &LeanPromptAssemblyRow) -> Message {
    match (row.role.as_str(), row.kind.as_str()) {
        ("assistant", _) => Message::Assistant {
            id: None,
            content: row.content.iter().map(assistant_item).collect(),
        },
        ("user", "toolResult") => {
            let [id] = row.call_ids.as_slice() else {
                panic!("a toolResult row must carry exactly one call id: {row:?}");
            };
            Message::User {
                content: vec![UserContent::ToolResult(ToolResult {
                    id: call_key(*id),
                    call_id: Some(call_key(*id)),
                    content: vec![ToolResultContent::Text(Text {
                        text: format!("{}-result", call_key(*id)),
                    })],
                })],
            }
        }
        ("user", _) => Message::User {
            content: row.content.iter().map(user_item).collect(),
        },
        (role, kind) => panic!("generated row has an unmodeled role/kind: {role}/{kind}"),
    }
}

fn assistant_item(item: &LeanPromptAssemblyItem) -> AssistantContent {
    match item.item.as_str() {
        "text" => AssistantContent::Text(Text {
            text: text_body(item.value),
        }),
        "other" => AssistantContent::Reasoning(Reasoning::new(&reasoning_body(item.value))),
        "call" => AssistantContent::ToolCall(tool_call(item.value)),
        other => panic!("generated content item has an unmodeled tag: {other}"),
    }
}

fn user_item(item: &LeanPromptAssemblyItem) -> UserContent {
    match item.item.as_str() {
        "text" => UserContent::Text(Text {
            text: text_body(item.value),
        }),
        other => panic!("generated user content item has an unmodeled tag: {other}"),
    }
}

/// Project a production `Message` back onto the model's row shape, so output
/// can be compared against the generated expectation on the model's own terms.
fn row_of_message(message: &Message) -> LeanPromptAssemblyRow {
    match message {
        Message::Assistant { content, .. } => {
            let items = content.iter().map(assistant_item_of).collect::<Vec<_>>();
            let call_ids = items
                .iter()
                .filter(|item| item.item == "call")
                .map(|item| item.value)
                .collect::<Vec<_>>();
            LeanPromptAssemblyRow {
                role: "assistant".to_string(),
                kind: if call_ids.is_empty() {
                    "ordinary".to_string()
                } else {
                    "assistantToolCalls".to_string()
                },
                call_ids,
                content: items,
            }
        }
        Message::User { content } => {
            let tool_results = content
                .iter()
                .filter_map(|item| match item {
                    UserContent::ToolResult(tool_result) => Some(tool_result),
                    _ => None,
                })
                .collect::<Vec<_>>();
            if tool_results.is_empty() {
                LeanPromptAssemblyRow {
                    role: "user".to_string(),
                    kind: "ordinary".to_string(),
                    call_ids: Vec::new(),
                    content: content.iter().map(user_item_of).collect(),
                }
            } else {
                assert_eq!(
                    tool_results.len(),
                    1,
                    "production threads exactly one tool result per user message \
                     (loop_stream.rs); the model's row projection assumes it"
                );
                LeanPromptAssemblyRow {
                    role: "user".to_string(),
                    kind: "toolResult".to_string(),
                    call_ids: vec![parse_call_key(&result_key(tool_results[0]))],
                    content: Vec::new(),
                }
            }
        }
        Message::System { .. } => {
            panic!("the PromptAssembly model has no system-row projection")
        }
    }
}

fn assistant_item_of(content: &AssistantContent) -> LeanPromptAssemblyItem {
    match content {
        AssistantContent::Text(text) => LeanPromptAssemblyItem {
            item: "text".to_string(),
            value: parse_suffix(&text.text, "text-"),
        },
        AssistantContent::ToolCall(tool_call) => LeanPromptAssemblyItem {
            item: "call".to_string(),
            value: parse_call_key(&call_key_of(tool_call)),
        },
        AssistantContent::Reasoning(reasoning) => LeanPromptAssemblyItem {
            item: "other".to_string(),
            value: parse_suffix(&reasoning_text(reasoning), "reasoning-"),
        },
        AssistantContent::Image(_) => {
            panic!("no witness row builds an image; projection would be ambiguous")
        }
    }
}

fn user_item_of(content: &UserContent) -> LeanPromptAssemblyItem {
    match content {
        UserContent::Text(text) => LeanPromptAssemblyItem {
            item: "text".to_string(),
            value: parse_suffix(&text.text, "text-"),
        },
        other => panic!("no witness row builds {other:?}; projection would be ambiguous"),
    }
}

fn reasoning_text(reasoning: &Reasoning) -> String {
    use gents::llm::message::ReasoningContent;
    reasoning
        .content
        .iter()
        .map(|block| match block {
            ReasoningContent::Text { text, .. } => text.clone(),
            other => panic!("unexpected reasoning block in a witness row: {other:?}"),
        })
        .collect::<Vec<_>>()
        .join("")
}

/// Mirrors `history.rs::tool_call_key`: `call_id` when present, else the item id.
fn call_key_of(tool_call: &ToolCall) -> String {
    tool_call
        .call_id
        .clone()
        .unwrap_or_else(|| tool_call.id.clone())
}

/// Mirrors `history.rs::tool_result_key`.
fn result_key(tool_result: &ToolResult) -> String {
    tool_result
        .call_id
        .clone()
        .unwrap_or_else(|| tool_result.id.clone())
}

fn parse_call_key(key: &str) -> u64 {
    parse_suffix(key, "call-")
}

fn parse_suffix(value: &str, prefix: &str) -> u64 {
    value
        .strip_prefix(prefix)
        .and_then(|rest| rest.parse::<u64>().ok())
        .unwrap_or_else(|| panic!("value {value:?} is not a generated {prefix}* identity"))
}

fn rows_of(messages: &[Message]) -> Vec<LeanPromptAssemblyRow> {
    messages.iter().map(row_of_message).collect()
}

fn messages_of(rows: &[LeanPromptAssemblyRow]) -> Vec<Message> {
    rows.iter().map(message_of_row).collect()
}

/// The projection must be faithful in both directions, or every comparison
/// below would be measuring the projection rather than the sanitizer.
#[test]
fn generated_rows_round_trip_through_production_messages() {
    let cases = lean_prompt_assembly_sanitize_cases();
    assert!(
        !cases.is_empty(),
        "Lean emitted no PromptAssembly sanitize cases"
    );
    for case in cases {
        for rows in [&case.input, &case.expected, &case.expected_twice] {
            assert_eq!(
                &rows_of(&messages_of(rows)),
                rows,
                "row -> Message -> row must be the identity ({})",
                case.name
            );
        }
    }
}

/// The fence. Drives the production sanitizer with generated input and compares
/// against the generated expectation, for the whole transcript, for a second
/// pass (idempotence), and for every suffix (split-stability).
#[test]
fn generated_sanitize_cases_drive_the_production_sanitizer() {
    let cases = lean_prompt_assembly_sanitize_cases();
    assert!(
        !cases.is_empty(),
        "Lean emitted no PromptAssembly sanitize cases"
    );

    for case in cases {
        let once = sanitize_history_for_provider(messages_of(&case.input));
        assert_eq!(
            rows_of(&once),
            case.expected,
            "sanitize disagrees with the Lean model on case {:?}",
            case.name
        );

        let twice = sanitize_history_for_provider(once.clone());
        assert_eq!(
            rows_of(&twice),
            case.expected_twice,
            "sanitize is not idempotent on case {:?}",
            case.name
        );

        for split in &case.splits {
            assert!(
                split.index <= case.input.len(),
                "generated split index {} exceeds input length on case {:?}",
                split.index,
                case.name
            );
            let suffix = messages_of(&case.input[split.index..]);
            assert_eq!(
                rows_of(&sanitize_history_for_provider(suffix)),
                split.expected,
                "sanitize disagrees with the Lean model on case {:?} at split {}",
                case.name,
                split.index
            );
        }
    }
}

/// Fence: the Messages SSE parser reproduces `ClaudeMap.mapTurn` on every
/// generated witness (mapped ids, empty-surface / unmapped / duplicate fail closed).
#[test]
fn generated_claude_map_cases_drive_the_messages_parser() {
    let cases = lean_prompt_assembly_claude_map_cases();
    assert!(
        !cases.is_empty(),
        "Lean emitted no PromptAssembly Claude map cases"
    );
    for case in cases {
        let surface: HashSet<String> = case.surface.iter().cloned().collect();
        let sse = claude_map_blocks_as_sse(&case.blocks);
        let parsed = parse_messages_sse(&sse, &surface);
        match case.outcome.as_str() {
            "ok" => {
                let events =
                    parsed.unwrap_or_else(|err| panic!("case {} should map: {err}", case.name));
                let got_ids: Vec<u64> = events
                    .iter()
                    .filter_map(|event| match event {
                        RawStreamingChoice::ToolCall(call) => {
                            Some(call.id.parse::<u64>().unwrap_or_else(|_| {
                                panic!("case {} mapped id {} is not a Nat", case.name, call.id)
                            }))
                        }
                        _ => None,
                    })
                    .collect();
                assert_eq!(got_ids, case.ids, "mapped ids ({})", case.name);
            }
            outcome => assert_fail_closed(&case.name, outcome, parsed),
        }
    }
}

/// Shared fail-closed oracle for the ClaudeMap and stream witnesses: the
/// Lean `errorName` tag must correspond to the parser's frozen Display text.
fn assert_fail_closed(
    case_name: &str,
    outcome: &str,
    parsed: Result<Vec<RawStreamingChoice<ClaudeStreamResponse>>, CompletionError>,
) {
    let err = parsed
        .expect_err("witness outcome is an error; parser must fail closed")
        .to_string();
    let ok = match outcome {
        "emptySurface" => err.contains("fail-closed: tool_use observed"),
        o if o.starts_with("unmappedName:") => {
            let name = o.strip_prefix("unmappedName:").expect("prefix");
            err.contains("fail-closed: tool_use observed") && err.contains(name)
        }
        o if o.starts_with("duplicateId:") => err.contains(&format!(
            "fail-closed: duplicate tool_use id {}",
            o.strip_prefix("duplicateId:").expect("prefix")
        )),
        o if o.starts_with("overlappingBlock:") => err.contains(&format!(
            "fail-closed: overlapping tool_use block {}",
            o.strip_prefix("overlappingBlock:").expect("prefix")
        )),
        other => panic!("case {case_name} unknown outcome {other}"),
    };
    assert!(
        ok,
        "case {case_name}: outcome {outcome} but error was: {err}"
    );
}

fn sse_event(payload: serde_json::Value) -> String {
    let kind = payload["type"].as_str().expect("type").to_string();
    format!("event: {kind}\ndata: {payload}\n\n")
}

/// Render ClaudeMap block tags (`text`, `toolUse:id:name`, `toolResult:id`) as
/// an assistant-turn SSE body. `toolResult` never appears in an assistant turn
/// and is skipped.
fn claude_map_blocks_as_sse(blocks: &[String]) -> String {
    let mut sse = String::new();
    for (index, block) in blocks.iter().enumerate() {
        if block == "text" {
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_start", "index": index,
                "content_block": {"type": "text", "text": ""}
            })));
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_delta", "index": index,
                "delta": {"type": "text_delta", "text": "hi"}
            })));
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_stop", "index": index
            })));
        } else if let Some(rest) = block.strip_prefix("toolUse:") {
            let (id, name) = rest
                .split_once(':')
                .unwrap_or_else(|| panic!("toolUse tag must be toolUse:id:name, got {block}"));
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_start", "index": index,
                "content_block": {"type": "tool_use", "id": id, "name": name, "input": {}}
            })));
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_stop", "index": index
            })));
        } else if block.starts_with("toolResult:") {
            continue;
        } else {
            panic!("unknown Claude map block tag {block}");
        }
    }
    sse.push_str(&sse_event(serde_json::json!({"type": "message_stop"})));
    sse
}

/// Fence: the Messages SSE parser reproduces `ClaudeMap.runStream` — deltas
/// win over the start input, overlap / duplicate / unmapped fail closed, an
/// unterminated block flushes at end of stream.
#[test]
fn generated_claude_stream_cases_drive_the_messages_parser() {
    let cases = lean_prompt_assembly_claude_stream_cases();
    assert!(
        !cases.is_empty(),
        "Lean emitted no PromptAssembly Claude stream cases"
    );
    for case in cases {
        let surface: HashSet<String> = case.surface.iter().cloned().collect();
        let sse = claude_stream_events_as_sse(&case.events);
        let parsed = parse_messages_sse(&sse, &surface);
        match case.outcome.as_str() {
            "ok" => {
                let events =
                    parsed.unwrap_or_else(|err| panic!("case {} should parse: {err}", case.name));
                let got: Vec<String> = events
                    .iter()
                    .filter_map(|event| match event {
                        RawStreamingChoice::ToolCall(call) => {
                            Some(format!("{}={}", call.id, call.arguments))
                        }
                        _ => None,
                    })
                    .collect();
                let want: Vec<String> = case
                    .calls
                    .iter()
                    .map(|entry| {
                        let (id, args) = entry.split_once('=').expect("id=args");
                        let value: serde_json::Value =
                            serde_json::from_str(args).unwrap_or_else(|err| {
                                panic!("case {} witness args {args}: {err}", case.name)
                            });
                        format!("{id}={value}")
                    })
                    .collect();
                assert_eq!(got, want, "calls ({})", case.name);
            }
            outcome => assert_fail_closed(&case.name, outcome, parsed),
        }
    }
}

/// Render `StreamEvent` tags as SSE. `start:<id>:<name>:<input>` with empty
/// input emits no `input` key (Lean `none`); a non-empty input is embedded as
/// the parsed JSON object.
fn claude_stream_events_as_sse(events: &[String]) -> String {
    let mut sse = String::new();
    for tag in events {
        if let Some(text) = tag.strip_prefix("text:") {
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_delta", "index": 0,
                "delta": {"type": "text_delta", "text": text}
            })));
        } else if let Some(rest) = tag.strip_prefix("start:") {
            let mut parts = rest.splitn(3, ':');
            let id = parts.next().expect("id");
            let name = parts.next().expect("name");
            let input = parts.next().unwrap_or("");
            let mut block = serde_json::json!({"type": "tool_use", "id": id, "name": name});
            if !input.is_empty() {
                block["input"] = serde_json::from_str(input)
                    .unwrap_or_else(|err| panic!("witness start input {input}: {err}"));
            }
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_start", "index": 0, "content_block": block
            })));
        } else if let Some(partial) = tag.strip_prefix("delta:") {
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_delta", "index": 0,
                "delta": {"type": "input_json_delta", "partial_json": partial}
            })));
        } else if tag == "stop" {
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_stop", "index": 0
            })));
        } else {
            panic!("unknown Claude stream event tag {tag}");
        }
    }
    sse
}

/// Fence: `build_messages_body_native` reproduces `ClaudeMap.systemBlocks` /
/// `splitSystem` / `toolsField` — identity first, preamble, then `System`
/// rows in order; `tools` absent for an empty surface.
#[test]
fn generated_claude_body_cases_drive_the_body_builder() {
    let cases = lean_prompt_assembly_claude_body_cases();
    assert!(
        !cases.is_empty(),
        "Lean emitted no PromptAssembly Claude body cases"
    );
    for case in cases {
        let history: Vec<Message> = case
            .rows
            .iter()
            .map(|row| {
                if let Some(text) = row.strip_prefix("system:") {
                    Message::System {
                        content: text.to_string(),
                    }
                } else if row == "other:assistant" {
                    Message::assistant("ok")
                } else {
                    Message::user("hi")
                }
            })
            .collect();
        let tools: Vec<rig::completion::ToolDefinition> = case
            .tools
            .iter()
            .map(|name| rig::completion::ToolDefinition {
                name: name.clone(),
                description: name.clone(),
                parameters: serde_json::json!({"type": "object"}),
            })
            .collect();
        let body = build_messages_body_native(
            "claude-sonnet-5",
            case.preamble.as_deref(),
            None,
            &history,
            &tools,
        );
        let system: Vec<String> = body["system"]
            .as_array()
            .unwrap_or_else(|| panic!("case {} system array: {body}", case.name))
            .iter()
            .map(|block| block["text"].as_str().expect("text").to_string())
            .collect();
        assert_eq!(system, case.system, "system blocks ({})", case.name);
        assert_eq!(system[0], CLAUDE_CODE_IDENTITY, "case {}", case.name);
        assert_eq!(
            body.get("tools").is_some(),
            case.tools_present,
            "tools key ({})",
            case.name
        );
        let leaked = body["messages"]
            .as_array()
            .expect("messages")
            .iter()
            .any(|message| {
                message["content"].as_array().is_some_and(|blocks| {
                    blocks.iter().any(|block| {
                        block["text"]
                            .as_str()
                            .is_some_and(|t| t.starts_with("system: "))
                    })
                })
            });
        assert!(
            !leaked,
            "System row leaked into messages ({}): {body}",
            case.name
        );
    }
}

/// Pairing identity: calls and results pair on `call_id.unwrap_or(id)`
/// (`history.rs::tool_call_key` / `tool_result_key`), never on the item id
/// alone. The Lean model abstracts both into one `ToolCallId`, so this
/// below-the-model identity is fenced only here: a pair whose `call_id` differs
/// from both item ids (the OpenAI responses-API shape) must survive sanitize.
#[test]
fn pairing_identity_uses_call_id_over_item_id() {
    let history = vec![
        Message::Assistant {
            id: None,
            content: vec![AssistantContent::ToolCall(ToolCall {
                id: "item-9".to_string(),
                call_id: Some("fc-1".to_string()),
                function: ToolFunction {
                    name: "echo".to_string(),
                    arguments: serde_json::json!({}),
                },
                signature: None,
                additional_params: None,
            })],
        },
        Message::User {
            content: vec![UserContent::ToolResult(ToolResult {
                id: "out-3".to_string(),
                call_id: Some("fc-1".to_string()),
                content: vec![ToolResultContent::Text(Text {
                    text: "fc-1-result".to_string(),
                })],
            })],
        },
    ];
    assert_eq!(sanitize_history_for_provider(history.clone()), history);
}

/// Below the model: a user message may carry plain content *and* tool results
/// in one message. The model's row projection has no such row (production
/// threads one result per message), so this shape is fenced only here.
#[test]
fn mixed_user_message_keeps_plain_content_and_drops_orphaned_result() {
    let history = vec![Message::User {
        content: vec![
            UserContent::Text(Text {
                text: "still here".to_string(),
            }),
            UserContent::ToolResult(ToolResult {
                id: "gone".to_string(),
                call_id: Some("gone".to_string()),
                content: vec![ToolResultContent::Text(Text {
                    text: "orphan".to_string(),
                })],
            }),
        ],
    }];
    assert_eq!(
        sanitize_history_for_provider(history),
        vec![Message::User {
            content: vec![UserContent::Text(Text {
                text: "still here".to_string(),
            })],
        }],
        "the orphaned result must go and the plain content must stay"
    );
}

// ---------------------------------------------------------------------------
// The owned-loop chokepoint.
//
// The claim `proofs/README.md` makes — and that `sanitize_history_for_provider`
// depends on — is that EVERY completion request in the system is born in the
// owned loop, which sanitizes loaded history at entry (`run_loop_stream`). The
// sanitize fence above is only worth anything if nothing bypasses it.
//
// Two source scans keep that honest. The first pins the set of files allowed to
// invoke a provider at all; a bypass would have to show up there. The second
// pins the set of files allowed to enter the owned loop, so a new completion
// path is visible in review rather than silent.
// ---------------------------------------------------------------------------

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .find(|path| path.join("crates/gents/proofs/lakefile.lean").exists())
        .expect("repository root should contain crates/gents/proofs/lakefile.lean")
        .to_path_buf()
}

/// Every non-test Rust source under `crates/gents/src`.
fn production_sources() -> Vec<(String, String)> {
    let root = repo_root();
    let src = root.join("crates/gents/src");
    let mut out = Vec::new();
    let mut stack = vec![src.clone()];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", dir.display()))
        {
            let path = entry.expect("readable dir entry").path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if path.extension().and_then(|ext| ext.to_str()) != Some("rs") {
                continue;
            }
            let relative = path
                .strip_prefix(&root)
                .expect("path under repo root")
                .to_string_lossy()
                .replace('\\', "/");
            // Test-only sources are not production call sites. Test code in
            // this crate lives in separate `tests.rs` files rather than inline
            // `#[cfg(test)]` modules, so excluding by path is sufficient — and
            // unlike truncating at the first `#[cfg(test)]`, it does not also
            // discard the file's real body (those markers sit at the top of
            // `loop_stream.rs` and `compaction.rs`, declaring `mod tests;`).
            if relative.ends_with("/tests.rs")
                || relative.contains("/tests/")
                || relative.contains("test_support")
                || relative.contains("lean_vocab_test")
            {
                continue;
            }
            let source = std::fs::read_to_string(&path)
                .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
            out.push((relative, source));
        }
    }
    out.sort();
    out
}

fn files_containing(needles: &[&str]) -> BTreeSet<String> {
    production_sources()
        .into_iter()
        .filter(|(_, source)| needles.iter().any(|needle| source.contains(needle)))
        .map(|(path, _)| path)
        .collect()
}

/// No completion request may be issued outside the owned loop and the admission
/// wrapper it passes through. A new file here means a provider call that never
/// saw `sanitize_history_for_provider` — report it before fixing it.
#[test]
fn provider_invocations_are_confined_to_the_owned_loop_seam() {
    let expected = BTreeSet::from([
        // Builds the request and sends it — the one owned-loop seam.
        "crates/gents/src/agent/loop_stream.rs".to_string(),
        // Wraps a model to apply admission control; receives an
        // already-assembled request from the owned loop.
        "crates/gents/src/admission/client.rs".to_string(),
    ]);
    let found = files_containing(&[".completion_request(", ".completion(", ".stream("]);
    assert_eq!(
        found, expected,
        "provider invocation escaped the owned-loop seam; every completion request \
         must be born in run_loop_stream, which sanitizes loaded history at entry"
    );
}

/// The owned loop's entry points. Sanitization happens once, at the top of
/// `run_loop_stream`; every production completion path must come through here.
#[test]
fn owned_loop_entry_points_are_registered() {
    let expected = BTreeSet::from([
        // Text and typed helpers wrap `run_loop_stream`.
        "crates/gents/src/agent/loop_stream/one_shot.rs".to_string(),
        // Daemon request execution — the main path.
        "crates/gents/src/agent/daemon/inference.rs".to_string(),
        // Conversation title generation.
        "crates/gents/src/agent/daemon/title.rs".to_string(),
        // Compaction summarization.
        "crates/gents/src/compaction.rs".to_string(),
        // One-shot CLI runs.
        "crates/gents/src/oneshot.rs".to_string(),
    ]);
    let found = files_containing(&[
        "run_loop_stream(",
        "run_loop_to_text(",
        "run_loop_to_typed(",
    ]);
    assert_eq!(
        found, expected,
        "the set of owned-loop entry points changed; a new completion path must be \
         reviewed against the sanitize-at-entry chokepoint"
    );
}
