//! Pure-Rust consumer of the exact immutable ToolFact foundation model (#1073).
//! Production schema/writer/projection cutover is deliberately deferred.

use crate::lean_vocab_test::{lean_tool_fact_cases, LeanToolFactCase};

#[allow(clippy::too_many_arguments)]
fn witness(
    name: &str,
    operation: &str,
    disposition: &str,
    twins: usize,
    full_output: bool,
    approval: bool,
    result_durable: bool,
    approval_durable: bool,
    projection: bool,
    immutable_noop: bool,
    call_signer: u64,
    result_cid: u64,
) -> LeanToolFactCase {
    LeanToolFactCase {
        name: name.to_owned(),
        operation: operation.to_owned(),
        disposition: disposition.to_owned(),
        visible_logical_twins: twins,
        full_output,
        call_doc_id: 100,
        call_cid: 10,
        call_signer_did: call_signer,
        result_doc_id: 200,
        result_cid,
        result_signer_did: 8,
        approval_doc_id: approval.then_some(300),
        approval_cid: approval.then_some(30),
        approval_signer_did: approval.then_some(9),
        result_durable,
        approval_durable,
        result_pins_exact_call: result_durable,
        approval_pins_exact_call: approval_durable,
        exact_projection: projection,
        immutable_noop,
    }
}

pub(super) fn generated_cases_pin_exact_immutable_tool_facts() {
    let expected = [
        witness(
            "call_fact_applied",
            "commit_call",
            "applied",
            0,
            true,
            false,
            false,
            false,
            false,
            false,
            7,
            20,
        ),
        witness(
            "identical_call_replay_is_idempotent",
            "commit_call",
            "observed_identical",
            1,
            true,
            false,
            false,
            false,
            false,
            true,
            7,
            20,
        ),
        witness(
            "logical_key_call_twins_fail_closed",
            "commit_call",
            "rejected",
            2,
            true,
            false,
            false,
            false,
            false,
            true,
            7,
            20,
        ),
        witness(
            "unsigned_call_is_rejected",
            "commit_call",
            "rejected",
            0,
            true,
            false,
            false,
            false,
            false,
            true,
            7,
            20,
        ),
        witness(
            "full_result_applied",
            "commit_result",
            "applied",
            0,
            true,
            false,
            true,
            false,
            true,
            false,
            7,
            20,
        ),
        witness(
            "identical_result_replay_is_idempotent",
            "commit_result",
            "observed_identical",
            1,
            true,
            false,
            true,
            false,
            true,
            true,
            7,
            20,
        ),
        witness(
            "mismatched_result_replay_is_rejected",
            "commit_result",
            "rejected",
            1,
            true,
            false,
            true,
            false,
            true,
            true,
            7,
            20,
        ),
        witness(
            "logical_key_result_twins_fail_closed",
            "commit_result",
            "rejected",
            2,
            true,
            false,
            false,
            false,
            false,
            true,
            7,
            20,
        ),
        witness(
            "incomplete_output_is_rejected",
            "commit_result",
            "rejected",
            0,
            false,
            false,
            false,
            false,
            false,
            true,
            7,
            20,
        ),
        witness(
            "unsigned_result_is_rejected",
            "commit_result",
            "rejected",
            0,
            true,
            false,
            false,
            false,
            false,
            true,
            7,
            20,
        ),
        witness(
            "approval_applied_with_exact_call",
            "commit_approval",
            "applied",
            0,
            true,
            true,
            true,
            true,
            true,
            false,
            7,
            20,
        ),
        witness(
            "identical_approval_replay_is_idempotent",
            "commit_approval",
            "observed_identical",
            1,
            true,
            true,
            true,
            true,
            true,
            true,
            7,
            20,
        ),
        witness(
            "logical_key_approval_twins_fail_closed",
            "commit_approval",
            "rejected",
            2,
            true,
            true,
            true,
            false,
            false,
            true,
            7,
            20,
        ),
        witness(
            "wrong_result_cid_projection_is_rejected",
            "project",
            "not_attempted",
            1,
            true,
            true,
            true,
            true,
            false,
            true,
            7,
            21,
        ),
        witness(
            "wrong_call_signer_projection_is_rejected",
            "project",
            "not_attempted",
            1,
            true,
            true,
            true,
            true,
            false,
            true,
            77,
            20,
        ),
    ];

    assert_eq!(lean_tool_fact_cases(), expected);
    assert!(expected
        .iter()
        .filter(|row| row.disposition == "rejected")
        .all(|row| row.immutable_noop));
}
